### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Avizacherman** [soitbros/regicide#1]
Clint,

You did it! Is your fiance happy with the outcome? I know you had some features you didn't get to but feel free to spend time refactoring your code and continuing to work on it until you get it exactly where you want it. 

One thing I did notice is that when you lose the game it prompts you to restart. When you hit ok, the game itself doesn't restart. So if you try to tally again it does the same prompt then creates another new restart button. How could you have avoided this?

Overall I like that you used an original concept, taught yourself to shuffle an array and built a nice looking client-facing game. Great work.

**Comment by ajhofferber** [comment]
Hey Clint,

I agree with Avi.  Your project turned out great and I think you ought to be proud of what you were able to build. And I also agree that we would love to see you do some refactoring of your code to build in any features you had hoped to include in your project.  But as it stands now, it totally meets requirements and you've put together a polished piece of work!

I would love to see you add both some screenshots of your game and a URL link to your gh-pages where your game is hosted. It would be awesome to make sure everyone rummaging through your github can see all of your hard work straight away!

Keep it uppppppp!

Score: 2 (refer to project 1 markdown in class repo for scoring rubric)

-Ash
